### PR TITLE
Fix edge cases

### PR DESCRIPTION
**Pull request by MSch**
I found lots of situations where the displayed cursor was wrong. This fixes them I think.

### CODE REVIEW

**Comment by oiva** [comment]
This seems to at least fix the bug where a block cursor would be shown in insert mode when switching back to Sublime Text from another program. This alone is great. What other situations were there?

**Comment by MSch** [comment]
IIRC there were situations where the block cursor continued to be shown after insert mode was left. But now that I looked at my commit again I'm not so sure.

**Comment by jondkinney** [comment]
+1 for a merge, working well for me here!

**Comment by fedesilvaponte** [comment]
Excelletn +1 for a merge too

**Comment by netpro2k** [comment]
Sorry this took so long to get in guys, been cheating on sublimetext with vim again for past few months. Giving it another go!

**Pull request merged**
